"""update tabel user new

Revision ID: 2e285b4d2b38
Revises: 7f27c1074379
Create Date: 2024-08-12 15:53:49.831519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e285b4d2b38'
down_revision = '7f27c1074379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BigInteger(), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('dosen', 'mahasiswa'), nullable=False))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
