"""update tabel user new

Revision ID: 779da27d1337
Revises: 2e285b4d2b38
Create Date: 2024-08-12 16:03:04.510092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '779da27d1337'
down_revision = '2e285b4d2b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('nim')
        batch_op.drop_column('nim')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nim', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index('nim', ['nim'], unique=True)

    # ### end Alembic commands ###
