"""Deskripsi migrasi terbaru

Revision ID: 7f27c1074379
Revises: 84806eb62061
Create Date: 2024-08-06 21:45:37.159128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f27c1074379'
down_revision = '84806eb62061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nim', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.Enum('dosen', 'mahasiswa'), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['nim'])
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_login', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('nim')

    # ### end Alembic commands ###
